### ISSUE TITLE
Hey thanks for the port, do we need certs?

### ISSUE THREAD

**Issue by kgrosvenor** [San-Jeevan/AppleReceiptVerifierCore#1]
Just a quick question, are p12  certificates not required for this?

**Comment by San-Jeevan** [comment]
No. Just run the code. It will send REST call on apples endpoint.

**Comment by kgrosvenor** [comment]
Thank you, is it possible to submit to NuGet?

**Comment by San-Jeevan** [comment]
I don't know how, I have never done it. I can give you ownership of this repo if you want to do it?

**Comment by kgrosvenor** [comment]
It's okay I managed to download and add a reference 😜 I'm a bit unsure
myself to be honest, I'll look into it
